language: python
cache:
  directories:
    - /tmp/travis-cache

# List of environment variable combinations to test against (first dimension)
# https://zato.io/docs/admin/guide/install/index.html#operating-system-considerations
env:
  # For later use with matrix.include later and OS X.
  - MODE=alembic
  #- MODE=packaging IMAGE=
  #- MODE=packaging IMAGE=centos:6
  #- MODE=packaging IMAGE=centos:7
  #- MODE=packaging IMAGE=ubuntu:12.04
  #- MODE=packaging IMAGE=ubuntu:14.04
  #- MODE=packaging IMAGE=i386/ubuntu:14.04
  #- MODE=packaging IMAGE=ubuntu:16.04
  #- MODE=packaging IMAGE=debian:7
  #- MODE=packaging IMAGE=debian:8
  #- MODE=packaging IMAGE=debian:9
  #- MODE=packaging IMAGE=alpine:3.7

# List of operating systems to test under (second dimension)
# https://docs.travis-ci.com/user/reference/overview/
sudo: required
os:
  - linux
  #- osx

# List of matrix exclusions
matrix:
  allow_failures:
    # Don't fail the build for a problem with OS X
    - osx

notifications:
  email: false

before_install:
  # https://github.com/travis-ci/travis-ci/issues/7940
  - sudo rm -f /etc/boto.cfg

script:
  - source .travis/test_${MODE}.sh
